name: Build and Publish Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: RimworldExtractor.sln
      Script_Path: tools.py

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Generate Change Log
      id: changelog
      uses: mathieudutour/github-tag-action@v6.1
      with:
          github_token: ${{ secrets.GH_ACTION_SECRET }}
          tag_prefix: ""
          release_branches: .*

    - name: Pre-Cleanup / Write Current Version
      id: cleanup
      run: |
        python $env:Script_Path utf8
        python $env:Script_Path version ${{ steps.changelog.outputs.new_tag }}
        python $env:Script_Path template "${{ steps.changelog.outputs.changelog }}"
      
    - name: Publish / Post-Cleanup
      run: |
        dotnet publish $env:Solution_Name -c Release -p:PublishDir=${{github.workspace}}/publish_standard
        dotnet publish $env:Solution_Name -c Release -p:PublishDir=${{github.workspace}}/publish_portable -p:PublishProtocol=FileSystem -p:TargetFramework=net7.0-windows -r win-x64 --self-contained true  -p:PublishSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:PublishDir=${{github.workspace}}/publish_portable
        python $env:Script_Path cleanup
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACTION_SECRET }}
      with:
        tag_name: ${{ steps.changelog.outputs.new_tag }}
        draft: false
        prerelease: false
        files: |
          RimworldExtractor-Standard.zip
          RimworldExtractor-Portable.exe
        body_path: .github/release_template.txt
